using Microsoft.EntityFrameworkCore;

namespace RAR.DAL.Model.Tabella
{
    public interface IRARContext
    {
        DbSet<AggiornaIntesaFiliali> AggiornaIntesaFiliali { get; set; }
        DbSet<AmbitoProvinciale> AmbitoProvinciale { get; set; }
        DbSet<ArchivioRelata> ArchivioRelata { get; set; }
        DbSet<Banca> Banca { get; set; }
        DbSet<CapDistinti> CapDistinti { get; set; }
        DbSet<CapparioUffici> CapparioUffici { get; set; }
        DbSet<Cliente> Cliente { get; set; }
        DbSet<CodiciSmarriti> CodiciSmarriti { get; set; }
        DbSet<CodiciTt> CodiciTt { get; set; }
        DbSet<ComunicazioneEsiti> ComunicazioneEsiti { get; set; }
        DbSet<Concessione> Concessione { get; set; }
        DbSet<ConcessioniAttive> ConcessioniAttive { get; set; }
        DbSet<ConfigCmp> ConfigCmp { get; set; }
        DbSet<ConfigCodiceEsito> ConfigCodiceEsito { get; set; }
        DbSet<ConfigCodiciCmp> ConfigCodiciCmp { get; set; }
        DbSet<ConfigFlagArData> ConfigFlagArData { get; set; }
        DbSet<ConfigFlagElab> ConfigFlagElab { get; set; }
        DbSet<ConfigFlagEsito> ConfigFlagEsito { get; set; }
        DbSet<ConfigFlagFonteEsito> ConfigFlagFonteEsito { get; set; }
        DbSet<ConfigFlagSottoEsito> ConfigFlagSottoEsito { get; set; }
        DbSet<ConfigFlagStatoComunicazione> ConfigFlagStatoComunicazione { get; set; }
        DbSet<ConfigFlagStatoLav> ConfigFlagStatoLav { get; set; }
        DbSet<ConfigFlagStatoLavAr> ConfigFlagStatoLavAr { get; set; }
        DbSet<ConfigFlagStatoPlico> ConfigFlagStatoPlico { get; set; }
        DbSet<ConfigFlagStatoScatola> ConfigFlagStatoScatola { get; set; }
        DbSet<ConfigFlagStatoScatolaRitorno> ConfigFlagStatoScatolaRitorno { get; set; }
        DbSet<ConfigFlagTipoAcquisizione> ConfigFlagTipoAcquisizione { get; set; }
        DbSet<ConfigFlagTipoPersona> ConfigFlagTipoPersona { get; set; }
        DbSet<ConfigFlagTipoScatola> ConfigFlagTipoScatola { get; set; }
        DbSet<ConfigFlagTipoScatolaRitorno> ConfigFlagTipoScatolaRitorno { get; set; }
        DbSet<ConfigLogicaRendicontazione> ConfigLogicaRendicontazione { get; set; }
        DbSet<ConfigMotiviRestituzione> ConfigMotiviRestituzione { get; set; }
        DbSet<ConfigMotivoScartoAr> ConfigMotivoScartoAr { get; set; }
        DbSet<ConfigRangePenali> ConfigRangePenali { get; set; }
        DbSet<ConfigSostFlagStato> ConfigSostFlagStato { get; set; }
        DbSet<ConfigSostFlagStatoScatola> ConfigSostFlagStatoScatola { get; set; }
        DbSet<ConfigSostFlagStatoTt> ConfigSostFlagStatoTt { get; set; }
        DbSet<ConfigStatoFlusso> ConfigStatoFlusso { get; set; }
        DbSet<ConfigStatoRacc> ConfigStatoRacc { get; set; }
        DbSet<ConfigTipoAnomalia> ConfigTipoAnomalia { get; set; }
        DbSet<ConfigTipoConsegna> ConfigTipoConsegna { get; set; }
        DbSet<ConsegnatoCmpService> ConsegnatoCmpService { get; set; }
        DbSet<DatiFlashNews> DatiFlashNews { get; set; }
        DbSet<DenominazioneSociale> DenominazioneSociale { get; set; }
        DbSet<Dipendenze> Dipendenze { get; set; }
        DbSet<DispaccioIn> DispaccioIn { get; set; }
        DbSet<DispaccioOut> DispaccioOut { get; set; }
        DbSet<DistintaPostel> DistintaPostel { get; set; }
        DbSet<DistintaPostelStorico> DistintaPostelStorico { get; set; }
        DbSet<EsaRacc> EsaRacc { get; set; }
        DbSet<EsaRaccBkp> EsaRaccBkp { get; set; }
        DbSet<EsaRaccCmp> EsaRaccCmp { get; set; }
        DbSet<EsaRaccStore> EsaRaccStore { get; set; }
        DbSet<EsaRaccStorico> EsaRaccStorico { get; set; }
        DbSet<EsaRaccTipoConsegna> EsaRaccTipoConsegna { get; set; }
        DbSet<EsitiDaFiliali> EsitiDaFiliali { get; set; }
        DbSet<EsitiDaFilialiSenzadata> EsitiDaFilialiSenzadata { get; set; }
        DbSet<FileLivorno> FileLivorno { get; set; }
        DbSet<Filiali> Filiali { get; set; }
        DbSet<GamAvvisiMoraIntesa> GamAvvisiMoraIntesa { get; set; }
        DbSet<GamCodiciTt> GamCodiciTt { get; set; }
        DbSet<GsAccettazioneArIncomplete> GsAccettazioneArIncomplete { get; set; }
        DbSet<GsDatiImgAr> GsDatiImgAr { get; set; }
        DbSet<GsRiepilogoScatole> GsRiepilogoScatole { get; set; }
        DbSet<GsSostitutiviAr> GsSostitutiviAr { get; set; }
        DbSet<ImgAr> ImgAr { get; set; }
        DbSet<ImgRelata> ImgRelata { get; set; }
        DbSet<IndicizzazioneEsaRacc> IndicizzazioneEsaRacc { get; set; }
        DbSet<LayoutStampanteZebra> LayoutStampanteZebra { get; set; }
        DbSet<LocalTemp> LocalTemp { get; set; }
        DbSet<Lotto> Lotto { get; set; }
        DbSet<MessiAnagrafica> MessiAnagrafica { get; set; }
        DbSet<MessoCodiciLivorno> MessoCodiciLivorno { get; set; }
        DbSet<MultiCap> MultiCap { get; set; }
        DbSet<MultiUfficio> MultiUfficio { get; set; }
        DbSet<NewAmbitoProvinciale> NewAmbitoProvinciale { get; set; }
        DbSet<NewAnagraficaFlussiPostel> NewAnagraficaFlussiPostel { get; set; }
        DbSet<NewBufferDistintaFittizia> NewBufferDistintaFittizia { get; set; }
        DbSet<NewBufferFileCorrotti> NewBufferFileCorrotti { get; set; }
        DbSet<NewBufferFileSelettivoCorrotti> NewBufferFileSelettivoCorrotti { get; set; }
        DbSet<NewCartolineDispaccioIn> NewCartolineDispaccioIn { get; set; }
        DbSet<NewCodeRaccStoricoCartelle> NewCodeRaccStoricoCartelle { get; set; }
        DbSet<NewCodiciAnomalia> NewCodiciAnomalia { get; set; }
        DbSet<NewCodiciCmp> NewCodiciCmp { get; set; }
        DbSet<NewCodiciErroriDaTt> NewCodiciErroriDaTt { get; set; }
        DbSet<NewDenominazioneSociale> NewDenominazioneSociale { get; set; }
        DbSet<NewDisguidi> NewDisguidi { get; set; }
        DbSet<NewDispacciJobCancellati> NewDispacciJobCancellati { get; set; }
        DbSet<NewDispaccioIn> NewDispaccioIn { get; set; }
        DbSet<NewElencoFileInput> NewElencoFileInput { get; set; }
        DbSet<NewElencoFileOutput> NewElencoFileOutput { get; set; }
        DbSet<NewElencoQuery> NewElencoQuery { get; set; }
        DbSet<NewEsitiDaTt> NewEsitiDaTt { get; set; }
        DbSet<NewEsitiDaTtBkp> NewEsitiDaTtBkp { get; set; }
        DbSet<NewEsitoCorretto> NewEsitoCorretto { get; set; }
        DbSet<NewFlussiInputRaw> NewFlussiInputRaw { get; set; }
        DbSet<NewFlussiOutputRaw> NewFlussiOutputRaw { get; set; }
        DbSet<NewImmagini> NewImmagini { get; set; }
        DbSet<NewImmaginiA99> NewImmaginiA99 { get; set; }
        DbSet<NewImmaginiPmr> NewImmaginiPmr { get; set; }
        DbSet<NewLavorazioneVerificaDistintaElettronica> NewLavorazioneVerificaDistintaElettronica { get; set; }
        DbSet<NewParametri> NewParametri { get; set; }
        DbSet<NewRendicontazioneCoordinateArchiviazioneNsin> NewRendicontazioneCoordinateArchiviazioneNsin { get; set; }
        DbSet<NewRendicontazioneEsitiNsin> NewRendicontazioneEsitiNsin { get; set; }
        DbSet<NewRendicontazioneImmaginiNsin> NewRendicontazioneImmaginiNsin { get; set; }
        DbSet<NewScambioEsitiTt> NewScambioEsitiTt { get; set; }
        DbSet<NewScambioNapoliImmagini> NewScambioNapoliImmagini { get; set; }
        DbSet<NewScartiTt> NewScartiTt { get; set; }
        DbSet<NewServiceRestituzioneAr> NewServiceRestituzioneAr { get; set; }
        DbSet<NewServiceRestituzioneCd> NewServiceRestituzioneCd { get; set; }
        DbSet<NewServiceRestituzioneCdScatola> NewServiceRestituzioneCdScatola { get; set; }
        DbSet<NewServiceRestituzioneFile> NewServiceRestituzioneFile { get; set; }
        DbSet<NewStagingPostelFlussi> NewStagingPostelFlussi { get; set; }
        DbSet<NewStagingPostelImmagini> NewStagingPostelImmagini { get; set; }
        DbSet<NewStoricoXmlTracciatura> NewStoricoXmlTracciatura { get; set; }
        DbSet<NewTipoesitoDaTt> NewTipoesitoDaTt { get; set; }
        DbSet<Param> Param { get; set; }
        DbSet<PatentiLibretti> PatentiLibretti { get; set; }
        DbSet<ProgressiviUtenteRipetuti> ProgressiviUtenteRipetuti { get; set; }
        DbSet<QualitaArLamezia> QualitaArLamezia { get; set; }
        DbSet<QualitaArVerona> QualitaArVerona { get; set; }
        DbSet<Query> Query { get; set; }
        DbSet<Querynew> Querynew { get; set; }
        DbSet<RaccAr> RaccAr { get; set; }
        DbSet<RaccEsitate> RaccEsitate { get; set; }
        DbSet<RaccPlichiMesso> RaccPlichiMesso { get; set; }
        DbSet<RaccTemp> RaccTemp { get; set; }
        DbSet<RendicontazioneMesso> RendicontazioneMesso { get; set; }
        DbSet<RiepilogoStorico> RiepilogoStorico { get; set; }
        DbSet<ScartatoGiornaliero> ScartatoGiornaliero { get; set; }
        DbSet<Scatola> Scatola { get; set; }
        DbSet<ScatolaAr> ScatolaAr { get; set; }
        DbSet<ScatolaRitorno> ScatolaRitorno { get; set; }
        DbSet<ServiceDispaccio> ServiceDispaccio { get; set; }
        DbSet<ServiceRestituzioneAr> ServiceRestituzioneAr { get; set; }
        DbSet<ServiceRestituzioneCd> ServiceRestituzioneCd { get; set; }
        DbSet<ServiceRestituzioneCdScatola> ServiceRestituzioneCdScatola { get; set; }
        DbSet<ServiceRestituzioneFile> ServiceRestituzioneFile { get; set; }
        DbSet<SostConfigRend> SostConfigRend { get; set; }
        DbSet<SostDati> SostDati { get; set; }
        DbSet<SostImg> SostImg { get; set; }
        DbSet<SostScatola> SostScatola { get; set; }
        DbSet<Sysdtslog90> Sysdtslog90 { get; set; }
        DbSet<TblPreavvisoCorrispondenza> TblPreavvisoCorrispondenza { get; set; }
        DbSet<TblPreavvisoRete> TblPreavvisoRete { get; set; }
        DbSet<TentatoRecapito> TentatoRecapito { get; set; }
        DbSet<TFlussi> TFlussi { get; set; }
        DbSet<TracciatureArVerona> TracciatureArVerona { get; set; }
        DbSet<TracciatureIncompletiArLamezia> TracciatureIncompletiArLamezia { get; set; }
        DbSet<TracciatureIncompletiArVerona> TracciatureIncompletiArVerona { get; set; }
        DbSet<TRaccInvioSelettivoPostel> TRaccInvioSelettivoPostel { get; set; }
        DbSet<ViarioUr> ViarioUr { get; set; }
        DbSet<XmlIndiceImgTemp> XmlIndiceImgTemp { get; set; }
        DbSet<XmlTemp> XmlTemp { get; set; }
        DbSet<XmlTempCorrotti> XmlTempCorrotti { get; set; }
        DbSet<XmlTempFittizia> XmlTempFittizia { get; set; }

        //Task<List<SpGetProductByPriceGreaterThan1000>> GetProductByPriceGreaterThan1000Async();
    }
}